-- Create a table for public profiles if needed (optional, but good practice)
create table profiles (
  id uuid references auth.users not null primary key,
  updated_at timestamp with time zone,
  username text unique,
  full_name text,
  avatar_url text,
  website text,

  constraint username_length check (char_length(username) >= 3)
);

-- Set up Row Level Security (RLS)
alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone." on profiles
  for select using (true);

create policy "Users can insert their own profile." on profiles
  for insert with check ((select auth.uid()) = id);

create policy "Users can update own profile." on profiles
  for update using ((select auth.uid()) = id);

-- This triggers a profile creation when a user signs up
create function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, username, full_name, avatar_url)
  values (new.id, new.raw_user_meta_data->>'username', new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();


-- WHITELISTS TABLE
create table whitelists (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null default auth.uid(),
  project text not null,
  x text, -- Twitter handle
  chain text not null check (chain in ('ETH', 'SOL', 'BTC', 'APE', 'BASE', 'ABS', 'Monad', 'HYPER')),
  type text not null check (type in ('GTD', 'FCFS', 'OG', 'WL')),
  wallets text,
  mint_date date,
  price text,
  mint_time time,
  mint_timezone text,
  priority text check (priority in ('High', 'Potential', 'Early')) default 'Potential',
  status text check (status in ('Not Minted', 'Minted')) default 'Not Minted',
  notes text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table whitelists enable row level security;

create policy "Individuals can create whitelists." on whitelists
  for insert with check ((select auth.uid()) = user_id);

create policy "Individuals can view their own whitelists." on whitelists
  for select using ((select auth.uid()) = user_id);

create policy "Individuals can update their own whitelists." on whitelists
  for update using ((select auth.uid()) = user_id);

create policy "Individuals can delete their own whitelists." on whitelists
  for delete using ((select auth.uid()) = user_id);


-- COLLABS TABLE
create table collabs (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null default auth.uid(),
  project text not null,
  twitter text,
  community text,
  spots text,
  contact text,
  team_spots text,
  giveaway_link text,
  winners text,
  status text check (status in ('Not Posted', 'Posted', 'Submitted', 'Cancel')) default 'Not Posted',
  due_at date,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table collabs enable row level security;

create policy "Individuals can create collabs." on collabs
  for insert with check ((select auth.uid()) = user_id);

create policy "Individuals can view their own collabs." on collabs
  for select using ((select auth.uid()) = user_id);

create policy "Individuals can update their own collabs." on collabs
  for update using ((select auth.uid()) = user_id);

create policy "Individuals can delete their own collabs." on collabs
  for delete using ((select auth.uid()) = user_id);
